n_gpu: 4

data_loader:
  type: FeatureDataloader
  args:
    num_workers: 8
    batch_size: 128
    shuffle: true
    drop_last: true
    dataset_name: 'MSRVTT'

    dataset_kwargs:
      data_path: './data/msrvtt/resnet/msrvtt_train.pkl'
      max_words: 20
      training: true
      n_video_tokens: 48
      num_audio_STFT_frames: 3072
      word2vec_path: './data/GoogleNews-vectors-negative300.bin'

val_data_loaders:
  - type: FeatureDataloader
    args:
      num_workers: 8
      batch_size: 8
      shuffle: false
      dataset_name: 'MSRVTT'

      dataset_kwargs:
        data_path: './data/msrvtt/resnet/msrvtt_jsfusion_test.pkl'
        max_words: 20
        training: false
        n_video_tokens: 48
        num_audio_STFT_frames: 3072
        word2vec_path: './data/GoogleNews-vectors-negative300.bin'


optimizer:
  type: Adam
  args:
    lr: 0.00005
lr_scheduler:
  type: ExponentialLR
  args:
    gamma: 0.9

loss:
  type: CombinatorialLoss
  args:
    tv_weight: 1
    ta_weight: 1
    va_weight: 1
    t_va_weight: 1
    v_ta_weight: 1
    a_tv_weight: 1

trainer:
  epochs: 25
  use_eval_mode_always: true
  resume_only_model: true
  mixed_precision: true
  save_dir: ./output
  save_period: 100
  verbosity: 2
  monitor: 'off'
  init_val: false
  neptune: false
