n_gpu: 4

data_loader:
  type: FeatureDataloader
  args:
    num_workers: 16
    batch_size: 16
    shuffle: false
    dataset_name: 'MSRVTT'

    dataset_kwargs:
      data_path: './data/msrvtt/resnet/msrvtt_jsfusion_test.pkl'
      data_path_2D: './data/msrvtt/clip/msrvtt_jsfusion_test.pkl'
      use_2D: True
      use_3D: False
      key_2d: 'clip'
      max_words: 20
      training: false
      n_video_tokens: 48
      num_audio_STFT_frames: 3072
      word2vec_path: './data/GoogleNews-vectors-negative300.bin'
